#!/usr/bin/env sh

unset VSCODE_HOME

[ -d "$HOME/.vscode" ] && VSCODE_HOME="$HOME/.vscode"
[ -d "$HOME/.vscode-oss" ] && VSCODE_HOME="$HOME/.vscode-oss"

[ -z "$VSCODE_HOME" ] && echo "ERROR: can't find vscode installation folder" && exit

[ ! -z "$VSCODE_HOME" ] && echo "found a vscode variant in $VSCODE_HOME"
EXT_INSTALL_NAME="mpab.$1-0.0.1-universal"
echo "removing $EXT_INSTALL_NAME..."
rm -rf "$VSCODE_HOME/extensions/$EXT_INSTALL_NAME"
rm -r "$VSCODE_HOME/extensions/extensions.json"
code --list-extensions
