#!/bin/zsh

export src_path=./src
export gen_path=./gen

echo $0 - src=$src_path, gen=$gen_path

rm -rf $gen_path
mkdir $gen_path

bison -v --output=$gen_path/parser.cc --defines=$gen_path/y.tab.h $src_path/parser.yy
# flex --outfile=$gen_path/lex.yy.cpp $src_path/lexer.l

echo "const char build_date[] = \"$(date)\";" > gen/build_date.h