#!/bin/bash
if [ ! -z $1 ]; then
    cd $1
    echo "building in '$1'..."
else
    echo "building in" $PWD"."
fi

./genfiles

rm -rf out
mkdir out
cd out

export SRCFILES="../src/main.cpp ../src/logger.cpp ../src/node.cpp ../src/context.cpp ../src/opcodes.cpp ../src/console.cpp ../gen/y.tab.cpp ../gen/lex.yy.cpp ../src/opcode_map.cpp"
export CPPFLAGS="-x c++ -Wno-write-strings -Wno-c++11-extensions"
g++ $CPPFLAGS $SRCFILES -o fluent
g++ -DDEBUG_BUILD $CPPFLAGS $SRCFILES -o dfluent
cp fluent ~/bin/
cp dfluent ~/bin/
